### ISSUE TITLE
Doesn't build on latest XCode

### ISSUE THREAD

**Issue by johnspurlock** [insidegui/WWDC-tvOS#3]
./WWDC-tvOS/WWDC/VideosViewController.swift:10:8: Module file was created by an older version of the compiler; rebuild 'RealmSwift' and try again: ./WWDC-tvOS/vendor/RealmSwift.framework/Modules/RealmSwift.swiftmodule/arm64.swiftmodule

Version 7.3 beta (7D152p)

**Comment by insidegui** [comment]
Always use the latest stable version of Xcode when working on this app. When the final 7.3 launches I'll check and fix any issues 😉

**Comment by johnspurlock** [comment]
Thanks, but I ended up just using this project instead, which did build and run.
https://github.com/azzoor/WWDCTV

Consider that ppl interested in something like this might be using a forward-looking xcode. :smiling_imp:

**Comment by insidegui** [comment]
I don't have the time nor the energy to test every single project I manage against every version of Xcode. Do whatever you want...
